### PR TITLE
set current max size to not exceed total elements

### PR DESCRIPTION
**Pull request by foochris**

### CODE REVIEW

**Comment by RoXuS** [comment]
Can you explain me in which case you need this condition?

**Comment by foochris** [comment]
It's a UI issue:

screen shot 2016-07-25 at 3 12 08 pm

**Comment by RoXuS** [comment]
So you just have to set the `totalElements` to 661 no ? Why you have 700 ?

**Comment by foochris** [comment]
`totalElements`is already set to 661, while `_computeCurrentMaxSize`is 700 because 

```
 size * (page + 1);
```

where size = 100 and page = 7

**Comment by RoXuS** [comment]
Oh yes, LGTM

**Pull request merged**
